version: "3"

services:

  # overpass:
  #   restart: always
  #   image: wiktorn/overpass-api:latest
  #   container_name: overpass0
  #   ports:
  #     - 12345:80
  #   env_file:
  #     - ./overpass.env
  #   volumes:
  #     - ./overpass_db:/db:rw

  valhalla:
    restart: always
    image: gisops/valhalla:latest
    ports:
      - 8002:8002
    env_file:
      - ./valhalla.env
    volumes:
      - ./valhalla_db/:/custom_files:rw

  redis:
    restart: always
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redis0
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    # command: redis-server
    ports:
      - 6379:6379
