"""
Django settings for pattern_detector project.

Generated by "django-admin startproject" using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY: str = "449i%6251wvar0pce1*6e3n-hqm+lykzp@!&7a&t!p8qv_yd95"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG: bool = True

ALLOWED_HOSTS: List[str] = []

AUTH_USER_MODEL: str = "backend.User"

# Application definition
DEFAULT_APPS: List[str] = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
]
EXTERNAL_APPS: List[str] = [
    "rest_framework",  # pip install djangorestframework
]
LOCAL_APPS: List[str] = [
    "backend",
]
INSTALLED_APPS: List[str] = DEFAULT_APPS + EXTERNAL_APPS + LOCAL_APPS

MIDDLEWARE: List[str] = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF: str = "stream_handler.urls"

TEMPLATES: List[Dict[str, Any]] = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

REST_FRAMEWORK: Dict[str, List[str]] = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
    ],
}

WSGI_APPLICATION: str = "pattern_detector.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES: Dict = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        "OPTIONS": {"timeout": 1000},
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS: List[Dict[str, Any]] = [
    {
        "NAME": "django.contrib.auth.password_validation.\
            UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.\
        MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.\
            CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.\
            NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE: str = "en-us"

TIME_ZONE: str = "UTC"

USE_I18N: bool = True

USE_L10N: bool = True

USE_TZ: bool = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL: str = "/static/"


# Trajectory anomaly detection settings
EPOCH: datetime = datetime.fromtimestamp(0).replace(tzinfo=None)
EARTH_RADIUS: float = 6371.0 * 1000.0  # In meters
PRIME_MERIDIAN_COORDS: List[float] = [  # In (lat, lon) coordinates
    51.477928,
    -0.001545,
]

# Queue name for: Main datapoint ingress queue
INGRESS_QUEUE: str = "ingress"
# Queue name for: Aggregation of datapoints
AGGREGATE_QUEUE: str = "aggregate"
# Queue name for: Filtered datapoints representing a trajectory
FILTER_QUEUE: str = "filter"
# Queue name for: Filtered datapoints working queue 0
PROCESS0_QUEUE: str = "process0"
# KV store name for: Current working trajectory
CURRENT_TRAJECTORY_KVSTORE: str = "current_trajectory"

# Stream handler namespace:
STREAMHANDLER_NAMESPACE: str = "DataPointStreamHandler"

# Forward loaction data to orther queues for further processing
# or the like
FORWARD_DATA: bool = False

# The size of the window we consider when calculating a
# similarity and anomaly score. For now set to a large value,
# such that we consider the whole sequence
TIMESERIES_WINDOW_SIZE: str = "1000T"
